"""Initial migration

Revision ID: 041882b2f2e8
Revises: 
Create Date: 2025-05-29 17:56:14.732989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041882b2f2e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
