# Dockerfile.celery
FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Копируем ВСЮ папку app внутрь контейнера
COPY app /app/app
ENV PYTHONPATH=/app
CMD ["celery", "-A", "app.app_celery.worker.celery_app", "worker", "--loglevel=info", "--pool=eventlet"]